if("undefined"===typeof window.AddShoppersTriggerRunner)window.AddShoppersTriggerRunner=function(){var w,r,x,s,j,F,t,p,u,v,k,y;function G(a){var b=typeof a;return null!=a&&("object"==b||"function"==b)}function P(a,b,c){function d(b){var c=q,d=f;q=f=void 0;j=b;return h=a.apply(d,c)}function H(a){var c=a-g,a=a-j;return void 0===g||c>=b||0>c||n&&a>=k}function e(){var a=Date.now();if(H(a))return i(a);var c=setTimeout,d=e,f;f=a-j;a=b-(a-g);f=n?Math.min(a,k-f):a;m=c(d,f)}function i(a){m=void 0;if(o&&q)return d(a);
q=f=void 0;return h}function l(){var a=Date.now(),c=H(a);q=arguments;f=this;g=a;if(c){if(void 0===m)return j=a=g,m=setTimeout(e,b),p?d(a):h;if(n)return m=setTimeout(e,b),d(g)}void 0===m&&(m=setTimeout(e,b));return h}var q,f,k,h,m,g,j=0,p=!1,n=!1,o=!0;if("function"!=typeof a)throw new TypeError(FUNC_ERROR_TEXT);b=+b||0;G(c)&&(p=!!c.leading,k=(n="maxWait"in c)?Math.max(+c.maxWait||0,b):k,o="trailing"in c?!!c.trailing:o);l.cancel=function(){void 0!==m&&clearTimeout(m);j=0;q=g=f=m=void 0};l.flush=function(){return void 0===
m?h:i(Date.now())};return l}function I(a){for(var b=0,c=0;c<a.length;c++)var d=a[c],b=b+d.price*d.quantity;return b}function z(a){localStorage.setItem("asCartContents",JSON.stringify({contents:a,timestamp:(new Date).getTime()}))}function A(){try{var a=JSON.parse(localStorage.getItem("asCartContents"));return a.timestamp<(new Date).getTime()-6048E5?(z([]),[]):a.contents||[]}catch(b){return z([]),[]}}function B(){try{return JSON.parse(localStorage.getItem("asProductViewHistory"))||[]}catch(a){return[]}}
function J(){if("function"===typeof window.asIsProductPage)try{var a=window.asIsProductPage();if(a){try{_add.push({browsed_products:[a],replace_cart_contents:!1})}catch(b){console.error(b)}var c=(new Date).getTime(),d=B().filter(function(a){return a.time>c-864E5});d.push({time:c,product:a});localStorage.setItem("asProductViewHistory",JSON.stringify(d))}}catch(e){console.log(e)}}function C(a){switch(a){case "minute":case "minutes":return 6E4;case "hour":case "hours":return 36E5;case "day":case "days":return 864E5;
default:return 1E3}}function i(a,b,c){switch(c){case "is":return a===b;case "is-not":return a!==b;case "less-than":return a<b;case "greater-than":return a>b;case "less-than-or-eq":return a<=b;case "greater-than-or-eq":return a>=b;default:return!1}}function n(a){if(null!=a.combinator)switch(a.combinator){case "all":for(var b=a.rules,c=0;c<b.length;c++)if(!n(a.rules[c]))return!1;return!0;case "any":b=a.rules;for(c=0;c<b.length;c++)if(n(a.rules[c]))return!0;return!1;case "one":for(var b=a.rules,d=0,
c=0;c<b.length;c++)n(a.rules[c])&&d++;return 1===d;case "none":b=a.rules;for(c=0;c<b.length;c++)if(n(a.rules[c]))return!1;return!0;default:return!1}switch(a.field){case "cart-value":return i(I(A()),a.value,a.operator);case "cart-count":return i(A().length,a.value,a.operator);case "logged-in":return!!w;case "device":switch(a.operator){case "is":return r===a.value;case "is-not":return r!==a.value;default:return!1}case "product-views":b=B();if("number"===typeof a.value)return i(b.length,a.value,a.operator);
for(var c=a.value.count,d=a.value.duration,e=C(a.value.unitOfTime),d=(new Date).getTime()-d*e,e=b.length-1,f=0;-1<e;)if(b[e].time>=d)f++,e--;else break;return i(f,c,a.operator);case "page-views":return"number"===typeof x?i(x,a.value,a.operator):!1;case "url-history":return b=document.URL.search(a.value.value),"is"==a.operator?"-1"!=b?!0:!1:"is-not"==a.operator?"-1"==b?!0:!1:!1;case "reward-points":return"number"===typeof s?i(s,a.value,a.operator):!1;case "percentage-scroll":return i(j,a.value,a.operator);
case "seconds-after-load":return Date.now()>=F+1E3*a.value;case "total-time-on-site":return K.setHasRule(!0),c=t,"number"===typeof a.value?(b=a.value,d="seconds"):(b=a.value.duration,d=a.value.unitOfTime),d=C(d),i(c,b*d,a.operator);case "is-recent-session":return c=parseInt(localStorage.getItem("isErcEmail")),"number"===typeof a.value?(b=a.value,d="seconds"):(b=a.value.duration,d=a.value.unitOfTime),d=C(d),i((new Date).getTime()-b*d,c,a.operator);case "users-active-campaign":return i(o.getUsersActiveEmailCampaign(),
a.value,a.operator);case "user-actions":switch(a.operator){case "unfocus":return p;case "return-to-home":return u;case "navigate-away":return v;case "abandon":return k;default:return!1}default:return!1}}function L(a,b){if(null!=a.combinator)for(var c=a.rules,d=0;d<c.length;d++)L(a.rules[d],b);"seconds-after-load"===a.field&&b.push(1E3*a.value)}function Q(a,b){for(var c=0;c<a.length;c++)if(b(a[c]))return a[c];return null}function M(){var a=[];h.forEach(function(b){L(b.trigger,a)});g=a.filter(function(b,
c){return a.indexOf(b)===c&&null===Q(g,function(a){return a.delay===b})}).map(function(a){var c={timeout:setTimeout(function(){var a=g.indexOf(c);0<=a&&(g.splice(a,1),e())},a),delay:a};return c}).concat(g)}function e(){for(var a=[],b=0;b<h.length;b++){var c=h[b].cb;n(h[b].trigger)?c():a.push(h[b])}h=a;setTimeout(function(){v=u=k=p=!1},300)}function N(){var a=Number(localStorage.getItem("asPageViews")),a=isNaN(Number(a))?1:Number(a)+1;localStorage.setItem("asPageViews",a)}function D(){location.pathname.slice(1)!==
y&&(k=p=!1,u="/"===location.pathname,v=!0);y=location.pathname.slice(1);l.scrollTop=l.getScrollPercent();j=l.scrollTop;N();J();B();Date.now();g.forEach(function(a){clearTimeout(a.timeout)});g=[];M();e()}function R(a,b){for(var c=document.documentElement,d=document.body,e=b.split(","),f=0;f<e.length;f++){var g=e[f].toLowerCase();if("top"===g){var i=c&&c.scrollTop||d&&d.scrollTop||0;if(a.pageY<i)return!0}if("bottom"===g){var h=window.innerHeight||document.documentElement.clientHeight||document.body.clientHeight,
h=h+i;if(a.pageY>h)return!0}if("left"===g&&"0">=a.pageX||"right"===g&&a.pageX>=(document.documentElement.clientWidth||window.innerWidth||document.body.clientWidth))return!0}return!1}function O(a){a=a?a:window.event;R(a,"top")&&"select"!==a.target.nodeName.toLowerCase()&&(k=!0,e(),document.removeEventListener("mouseout",O))}function o(a,b){a&&a.rules&&0<a.rules.length&&(n(a)?b():(h.push({trigger:a,cb:b}),M()))}N();var l={settings:{},lastPos:null,newPos:null,timer:void 0,delta:0,delay:50,didAlert:!1,
scrollTop:0,clear:function(){this.lastPos=null;this.delta=0;if(!0===this.settings.resetOnClear)this.didAlert=!1},getDocHeight:function(){var a=document;try{return Math.max(a.body.scrollHeight,a.documentElement.scrollHeight,a.body.offsetHeight,a.documentElement.offsetHeight,a.body.clientHeight,a.documentElement.clientHeight)}catch(b){return Math.max(a.documentElement.scrollHeight,a.documentElement.offsetHeight,a.documentElement.clientHeight)}},getScrollPercent:function(){var a=window.innerHeight||
(document.documentElement||document.body).clientHeight,b=this.getDocHeight();return Math.floor(100*((window.pageYOffset||(document.documentElement||document.body.parentNode||document.body).scrollTop)/(b-a)))||0},checkScrollSpeed:function(){this.newPos=window.scrollY;var a=this.scrollTop;this.scrollTop=this.getScrollPercent();this.scrollTop!==a&&this.settings.scrollTask();if(null!==this.lastPos)this.delta=this.newPos-this.lastPos;this.lastPos=this.newPos;clearTimeout(this.timer);this.timer=setTimeout(this.clear.bind(this),
this.delay);if(this.delta<0-this.settings.alertThreshold&&!1===this.didAlert&&this.scrollTop>=this.settings.scrollThreshold)this.settings.alertTask(),this.didAlert=!0},init:function(a){this.settings=a||{alertThreshold:50,scrollThreshold:30,resetOnClear:!1,alertTask:function(){},scrollTask:function(){}};this.delay=this.settings.delay||50;window.addEventListener("scroll",this.checkScrollSpeed.bind(this))}},K={_localStorageSetTimeField:"asTimeOnSiteSetTime",_localStorageValueField:"asTimeOnSiteValue",
_localStorageExpirationPeriod:432E6,_intervalTimeout:1E3,_hasRule:!1,_lastSetTime:null,_value:0,init:function(){this._hasRule=!1;this._lastSetTime=(new Date).getTime();t=this._value=this._getValueFromLocalStorage();setInterval(this._intervalHandler.bind(this),this._intervalTimeout)},setHasRule:function(a){this._hasRule=!!a},_intervalHandler:function(){var a=(new Date).getTime();this._value+=a-this._lastSetTime;this._lastSetTime=a;t=this._value;this._saveValueToLocalStorage();this._hasRule&&e()},_getValueFromLocalStorage:function(){try{var a=
(new Date).getTime(),b=localStorage.getItem(this._localStorageSetTimeField),c=null==b||isNaN(Number(b))?a:Number(b);if(a-c<this._localStorageExpirationPeriod){var d=localStorage.getItem(this._localStorageValueField);return null==d||isNaN(Number(d))?0:Number(d)}}catch(e){}return 0},_saveValueToLocalStorage:function(){try{localStorage.setItem(this._localStorageValueField,this._value),localStorage.setItem(this._localStorageSetTimeField,this._lastSetTime)}catch(a){}}},h=[],g=[];F=Date.now();r=function(){var a=
navigator.userAgent.toLowerCase();return/ipad|tablet|playbook|silk/i.test(a)||"MacIntel"===navigator.platform&&1<navigator.maxTouchPoints||window.matchMedia("(min-width: 768px) and (max-width: 1024px)").matches?"tablet":/android|iphone|ipod|blackberry|iemobile|opera mini/i.test(a)?"mobile":"pc"}();y=location.pathname.slice(1);w=null;x=Number(localStorage.getItem("asPageViews"));s=null;j=0;p=!1;u=!1;v=!1;k=!1;t=0;l.scrollTop=l.getScrollPercent();j=l.scrollTop;var E=!1;try{E=window.top!==window.self}catch(U){E=
!0}E&&(k=!0,window.parent.postMessage({type:"minty-onsite-register-iframe",mintyIframeId:"minty-tracker-frame"},"*"));l.init({delay:5E3,alertThreshold:50,scrollThreshold:30,resetOnClear:!0,alertTask:function(){if("mobile"===r||"tablet"===r)k=!0,e()},scrollTask:function(a,b,c){var d=!0,e=!0;if("function"!=typeof a)throw new TypeError(FUNC_ERROR_TEXT);G(c)&&(d="leading"in c?!!c.leading:d,e="trailing"in c?!!c.trailing:e);return P(a,b,{leading:d,maxWait:b,trailing:e})}(function(){j=l.scrollTop;e()},200)});
if("undefined"!==typeof window.history){var f=window.history,S=f.pushState;f.pushState=function(a){if("function"==typeof f.onpushstate)f.onpushstate({state:a});var b=S.apply(f,arguments);D();return b};var T=f.replaceState;f.replaceState=function(a){var b=T.apply(f,arguments);D();return b};window.addEventListener("popstate",D)}window.addEventListener("blur",function(){p=!0;e()});document.addEventListener("mouseout",O,!1);window.addEventListener("message",function(a){if(a.data&&"string"===typeof a.data.type){var b=
a.data.type;if("minty-onsite-focus-lost"===b)p=!0,e();else if("minty-onsite-scroll-update"===b)j=a.data.scrollPercent,e()}});K.init();o.getUsersActiveEmailCampaign=function(){try{return localStorage.getItem("asUsersActiveEmailCampaign")}catch(a){return null}};o.updateUsersActiveEmailCampaign=function(a){var b=o.getUsersActiveEmailCampaign();null==b&&null==a||b===a||(localStorage.setItem("asUsersActiveEmailCampaign",a),setTimeout(e,0))};o.dataLayerLoaded=function(){try{if("function"===typeof window.asCart){var a=
function(a){return null==a||Array.isArray(a)?a:Symbol.iterator in Object(a)?Array.from(a):null},b=function(){var b;"function"===typeof window.asCartRows&&(b=a(window.asCartRows()));if("function"===typeof window.asCartItems&&(b=a(window.asCartItems(b))))z(b),_add&&_add.push&&(b=A(),_add.push({cart_contents:b,cart_value:I(b),active_cart:!0})),e()};window.asCart(b,b)}"function"===typeof window.asRewardPoints&&window.asRewardPoints(function(a){s=a;e()});"function"===typeof window.asLoggedIn&&window.asLoggedIn(function(a){w=
a;e()})}catch(c){console.log(c)}J();e()};return o}();
